apiVersion: v1
kind: Service
metadata:
  name: service-broker-service
  namespace: catalog
spec:
  selector:
    app: ccloud-service-broker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
